// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_middleware.ts";
import * as $1 from "./routes/index.tsx";
import * as $2 from "./routes/package/[...name].tsx";
import * as $3 from "./routes/random.ts";
import * as $$0 from "./islands/Search.tsx";

const manifest = {
  routes: {
    "./routes/_middleware.ts": $0,
    "./routes/index.tsx": $1,
    "./routes/package/[...name].tsx": $2,
    "./routes/random.ts": $3,
  },
  islands: {
    "./islands/Search.tsx": $$0,
  },
  baseUrl: import.meta.url,
};

export default manifest;
